# services:
#   api:
#     build: api
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

#   db:
#     build: db
#     ports:
#       - "6379:6379"
#     volumes:
#       - .data:/data

version: "3"

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - ./frontend/dist:/app/frontend/dist
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
